version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 10
    commands:
      - echo Installing angular cli...
      - npm install -g @angular/cli
      - yarn add @angular-devkit/build-angular --dev
  build:
    commands:
      - echo Build started...
      - ng build --prod
  post_build:
    commands:
      - cd dist
      - aws s3 cp $aws-S3-files-site s3://$shahaf-images-site --recursive
artifacts:
  files:
    - dist/**/*
